import 'package:flutter/material.dart';
import 'package:pro/main.dart';
import 'map.dart';
void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      routes: {
        '/pop': (context) => TrashInformation(),
        // '/common': (context) => Frame2(),
        // '/insea': (context) => const AboutKaya(),
        // '/recycle':(context) => TrashInformation(),
        // '/danger':(context) => TrashInformation(),
       '/' : (context) => const CustomWidget(),
      },
      initialRoute: '/',
    );
  }
}

class TrashInformation extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView (
      child: Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0x335E9D48)),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 103,
                  decoration: ShapeDecoration(
                    color: Color(0xFF5DA57A),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 2, color: Color(0xFF06D5F2)),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 52,
                top: 30,
                child: SizedBox(
                  width: 289,
                  height: 89,
                  child: Text(
                    'Trash Information',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Colors.white,
                      fontSize: 32,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w900,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned (
                left: 45,
                top: 158,
                child: Container(
                  width: 310,
                  height: 64,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 310,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: Color(0xFF2C59F6),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 1),
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 16,
                        child: SizedBox(
                          width: 310,
                          height: 48,
                          child: Text(
                            'ขยะทั่วไป',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              decoration: TextDecoration.none,
                              color: Colors.white,
                              fontSize: 24,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w900,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                 ),
                ),
              
              
              Positioned(
                left: 45,
                top: 250,
                child: Container(
                  width: 310,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 310,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: Color(0xFF28AA44),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 1),
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 13,
                        child: SizedBox(
                          width: 310,
                          child: Text(
                            'ขยะอินทรีย์',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              decoration: TextDecoration.none,
                              color: Colors.white,
                              fontSize: 24,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w900,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 445,
                child: Container(
                  width: 310,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 310,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: Color(0xFFBA5056),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 1),
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 12,
                        child: SizedBox(
                          width: 310,
                          height: 48,
                          child: Text(
                            'ขยะอันตราย',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              decoration: TextDecoration.none,
                              color: Colors.white,
                              fontSize: 24,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w900,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 629,
                child: GestureDetector(
                    onTap: () {
                    Navigator.pushNamed(context, '/');
                },
                child: Container(
                  width: 310,
                  height: 68,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 310,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: Color(0xFF427C7A),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 1),
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 20,
                        child: SizedBox(
                          width: 310,
                          height: 48,
                          child: Text(
                            'MENU',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              decoration: TextDecoration.none,
                              color: Colors.white,
                              fontSize: 24,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w900,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
               ),
              ),
              Positioned(
                left: 45,
                top: 349,
                child: Container(
                  width: 310,
                  height: 64,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 310,
                          height: 64,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 310,
                                  height: 60,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFBAA050),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1),
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 16,
                                child: SizedBox(
                                  width: 310,
                                  height: 48,
                                  child: Text(
                                    'ขยะรีไซเคิล',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      decoration: TextDecoration.none,
                                      color: Colors.white,
                                      fontSize: 24,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w900,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
     ),
    );
  }
}