import 'package:flutter/material.dart';
import 'package:pro/Trash_info.dart';
import 'package:pro/information/common.dart';
import 'package:pro/information/danger.dart';
import 'package:pro/information/recycle.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor:  const Color(0xFF28AA44),
      ),
      home: const Scaffold(
        body: Stack(
          children: [
            Positioned(
              top: 10,
              left: 10,
              right: 10,
              child: Group74(),
            ),
            Positioned(
              top: 170, 
              left: 0,
              right: 0,
              bottom: 0,
              child: SingleChildScrollView(
              child: Frame3(),
             ),
            ),
          ],
        ),
      ),
    );
  }
}

class TrashPictureInsea extends StatelessWidget {
  const TrashPictureInsea({super.key});

  @override
  Widget build(BuildContext context) {
    return const Expanded(
      child: Column(
          children: [
            Group74(),
            Frame3(),
          ],
        ),
    );
  }
}
class Group74 extends StatelessWidget {
  const Group74({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
          width: 400,
          height: 162,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 400,
                  height: 150,
                  decoration: const BoxDecoration(color: Color(0xFF28AA44)),
                ),
              ),
              Positioned(
                left: 0,
                top: 28,
                child: SizedBox(
                  width: 400,
                  height: 134,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 420,
                          height: 160,
                          decoration: const BoxDecoration(color: Color(0xFF28AA44)),
                        ),
                      ),
                      Positioned(
                        left: 8,
                        top: 76,
                        child: Container(
                          width: 393,
                          height: 58,
                          clipBehavior: Clip.antiAlias,
                          decoration: const BoxDecoration(),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 291,
                                top: 7,                               
                                child: SizedBox(
                                  width: 85.01,
                                  height: 36,
                                  child: GestureDetector(
                                     onTap: () {
                                     Navigator.push(
                                     context, 
                                     MaterialPageRoute(builder: (context) => const TrashPictureDanger()),
                                    );
                                  },
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 85.01,
                                          height: 36,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFEA2B4D),
                                            shape: RoundedRectangleBorder(
                                              side: const BorderSide(
                                                width: 1,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                              ),
                                              borderRadius: BorderRadius.circular(15),
                                            ),
                                          ),
                                        ),
                                      ),
                                      const Positioned(
                                        left: 6,
                                        top: 9,
                                        child: SizedBox(
                                          width: 73,
                                          height: 17,
                                          child: Text(
                                            'ขยะอันตราย',
                                            style: TextStyle(
                                              decoration: TextDecoration.none,
                                              color: Colors.white,
                                              fontSize: 12,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w900,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                   ),
                                  ),
                                ),                             
                              ),
                              Positioned(
                                left: 197,
                                top: 7,                               
                                child: SizedBox(
                                  width: 85.01,
                                  height: 36,
                                  child: GestureDetector(
                                    onTap: () {
                                     Navigator.push(
                                     context, 
                                     MaterialPageRoute(builder: (context) => const TrashPictureRecycle()),
                                   );
                                  },
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 85.01,
                                          height: 36,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFC4B212),
                                            shape: RoundedRectangleBorder(
                                              side: const BorderSide(
                                                width: 1,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                              ),
                                              borderRadius: BorderRadius.circular(15),
                                            ),
                                          ),
                                        ),
                                      ),
                                      const Positioned(
                                        left: 9,
                                        top: 10,
                                        child: SizedBox(
                                          width: 69,
                                          height: 17,
                                          child: Text(
                                            'ขยะรีไซเคิล',
                                            style: TextStyle(
                                              decoration: TextDecoration.none,
                                              color: Colors.white,
                                              fontSize: 12,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w900,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                               ),
                              ),
                              Positioned(
                                left: 102,
                                top: 7,
                                child: SizedBox(
                                  width: 85.01,
                                  height: 36,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 85.01,
                                          height: 36,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFF2DB796),
                                            shape: RoundedRectangleBorder(
                                              side: const BorderSide(
                                                width: 3,                                 
                                                color: Color(0xFF1ACD16)
                                              ),
                                              borderRadius: BorderRadius.circular(15),
                                            ),
                                          ),
                                        ),
                                      ),
                                      const Positioned(
                                        left: 9,
                                        top: 10,
                                        child: SizedBox(
                                          width: 68,
                                          height: 17,
                                          child: Text(
                                            'ขยะอินทรีย์',
                                            style: TextStyle(
                                              decoration: TextDecoration.none,
                                              color: Colors.white,
                                              fontSize: 12,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w900,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                               ),
                              Positioned(
                                left: 7.99,
                                top: 7,
                                child: SizedBox(
                                  width: 94.01,
                                  height: 36,
                                  child: GestureDetector(
                                     onTap: () {
                                     Navigator.push(
                                     context, 
                                     MaterialPageRoute(builder: (context) => const TrashPictureCommon()),
                                    );
                                  },
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 85.01,
                                          height: 36,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFF2685F4),
                                            shape: RoundedRectangleBorder(
                                              side: const BorderSide(
                                                width: 1,
                                                strokeAlign: BorderSide.strokeAlignOutside,
                                                color: Color(0xFF0B163D),
                                              ),
                                              borderRadius: BorderRadius.circular(15),
                                            ),
                                          ),
                                        ),
                                      ),
                                      const Positioned(
                                        left: 17.01,
                                        top: 9,
                                        child: SizedBox(
                                          width: 77,
                                          height: 17,
                                          child: Text(
                                            'ขยะทั่วไป',
                                            style: TextStyle(
                                              decoration: TextDecoration.none,
                                              color: Colors.white,
                                              fontSize: 12,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w900,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                             ),
                            ],
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 51,
                        top: 21,
                        child: SizedBox(
                          width: 289,
                          height: 89,
                          child: Text(
                            'KAYA',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              decoration: TextDecoration.none,
                              color: Colors.white,
                              fontSize: 32,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w900,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 14,
                child: SizedBox(
                  width: 63,
                  height: 24,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 23,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: const BoxDecoration(),
                          child: const Stack(children: [
                          
                          ]),
                        ),
                      ),
                      Positioned(
                        left: 18,
                        top: 10,
                        child: GestureDetector(
                          onTap: () {
                            Navigator.push(
                              context, 
                              MaterialPageRoute(builder: (context) => const TrashInformation()),
                            );
                          },
                        child: const SizedBox(
                          width: 45,
                          height: 18,
                          child: Text(
                            'BACK',
                            style: TextStyle(
                              decoration: TextDecoration.none,
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w600,
                              height: 0,
                            ),
                          ),
                        ),),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
    );
  }
}

class Frame3 extends StatelessWidget {
  const Frame3({super.key});

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: SingleChildScrollView(
      child: Column(
       children: [
        Container(
          width: 400,
          height: 1482,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Color(0xFF28AA44)),
          child: Stack(
            children: [
              const Positioned(
                left: 20,
                top: 1157,
                child: SizedBox(
                  width: 361,
                  child: Text(
                    'ซากสัตว์ที่ตายแล้ว หากทิ้งไว้ก็อาจจะส่งกลิ่นเหม็นให้กับสถานที่ๆนั้น ดังนั้นหากเราเห็นซากสัตว์ตายในสถานที่ๆมีผู้คน จึงควรนำมันมาทิ้ง',
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w900,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 935,
                child: Container(
                  width: 346,
                  height: 193,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/insea3.png"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 20,
                top: 895,
                child: SizedBox(
                  width: 361,
                  child: Text(
                    '3. ซากสัตว์',
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w900,
                      height: 0,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 20,
                top: 5,
                child: SizedBox(
                  width: 361,
                  height: 187,
                  child: Text(
                    'ขยะอินทรีย์คือสิ่งที่เกิดจากสิ่งมีชีวิตหรือมีส่วนประกอบ\nจากสิ่งมีชีวิต ซึ่งเมื่อถูกทิ้งทิ้งหรือทิ้งไปแล้วจะเกิดการเน่าเปื่อย หรือย่อยสลายอย่างธรรมชาติ และจะกลายเป็นปุ๋ยหรือรังสีเมืองหลังจากการย่อยสลายของจุลินทรีย์',
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w900,
                      height: 0,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 20,
                top: 159,
                child: SizedBox(
                  width: 361,
                  child: Text(
                    'ชนิดของขยะอินทรีย์มีอยู่หลักๆ 3 ชนิดดังนี้',
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w900,
                      height: 0,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 20,
                top: 208,
                child: SizedBox(
                  width: 361,
                  child: Text(
                    '1. เศษอาหาร  ',
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w900,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 243,
                child: Container(
                  width: 345,
                  height: 197,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/insea2.png"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 20,
                top: 450,
                child: SizedBox(
                  width: 361,
                  height: 85,
                  child: Text(
                    'เป็นขยะอินทรีย์ที่มาจากเศษอาหารหรือผลไม้ที่เราทิ้งทิ้ง เช่น เปลือกผลไม้หรือเนื้อผลไม้ที่เป็นขยะอินทรีย์',
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w900,
                      height: 0,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 20,
                top: 525,
                child: SizedBox(
                  width: 361,
                  child: Text(
                    '2. วัชพืช หรือพืชที่ตายแล้ว',
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w900,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 565,
                child: Container(
                  width: 346,
                  height: 192,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/insea1.png"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 20,
                top: 770,
                child: SizedBox(
                  width: 361,
                  height: 152,
                  child: Text(
                    'เป็นขยะอินทรีย์ที่มาจากวัชพืชหรือส่วนต่างๆของพืชที่\nตายแล้ว เช่น ใบไม้ที่ร่วงจากต้นไม้หรือกิ่งไม้ที่ตัดลงมา \nผักผลไม้ที่เน่าเสีย',
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w900,
                      height: 0,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
       ],
      ),
     ),
   );
  }
}